Essential common components
dump-hr/ddays-app pull request #15
Opened 2023-11-26 17:29 UTC by tsiklic1

Adding common components: Button, Input, Layout, Modal, Table

2023-11-27 15:10 UTC, bdeak4 requested changes

2023-11-27 20:18 UTC, tsiklic1 commented on apps/admin/src/components/Modal/Modal.tsx
> +  modal: boolean;
✅

2023-11-28 19:13 UTC, dujesa commented
Formatirat css

2023-11-28 20:40 UTC, AntimonDalmatinac commented on apps/admin/src/App.tsx
> +import EventsPage from "./pages/EventsPage";
**
![1_OARpkeBkn_Tw3vk8H769OQ](https://github.com/dump-hr/ddays-app/assets/152331329/0ff653be-aa61-4671-8957-aba9feb77b49)
ovo mos koristit**

2023-11-28 20:41 UTC, AntimonDalmatinac requested changes
triba vise od 1% docker tehnologije

2023-11-28 20:45 UTC, tsiklic1 commented on apps/admin/src/App.tsx
> +import EventsPage from "./pages/EventsPage";
✅

2023-12-03 17:05 UTC, merged