Sponsor tier limitations
dump-hr/ddays-app pull request #202
Opened 2024-02-06 19:55 UTC by fdoljanin

2024-02-06 22:28 UTC, bdeak4 requested changes

2024-02-06 22:28 UTC, bdeak4 commented on apps/api/db/migrations/meta/_journal.json
discardat ovo, nez zasto nije ignoriralo promjene

2024-02-06 22:28 UTC, bdeak4 commented on apps/sponsor/src/formSteps/Job/Job.tsx
> +          getMaxJobsPerTier(company?.category as CompanyCategory) && (
ovaj cast je pretpostavljam zato sta company može bit null, rađe bi samo stavia da je parametar u funkciju nullable nego ovako lagao TS da je uvik CompanyCategory

2024-02-06 22:28 UTC, bdeak4 commented on apps/sponsor/src/pages/MaterialsPage/MaterialsPage.tsx
> +      {company && (
umjesto ovoga bolje izbit u if iznad i dodat loading... ili slicno

2024-02-06 22:28 UTC, bdeak4 commented on packages/types/src/dto/company.ts
> +  @IsString()
ovdje isto valjda treba bit isOptional jer inace nece proc save na modalu?

2024-02-10 20:19 UTC, fdoljanin commented on packages/types/src/dto/company.ts
> +  @IsString()
oce jer salje prazni string al moze

2024-02-10 20:25 UTC, fdoljanin commented on apps/sponsor/src/pages/MaterialsPage/MaterialsPage.tsx
> +      {company && (
pa ima mi vise smisla da je layout vidljiv dok se loada stranica nego samo loading?

2024-02-10 20:25 UTC, fdoljanin commented on apps/sponsor/src/pages/MaterialsPage/MaterialsPage.tsx
> +      {company && (
msm mogu ponovit cijeli kod gore al to mi se cini nesretnije

2024-02-10 20:27 UTC, fdoljanin commented on apps/sponsor/src/formSteps/Job/Job.tsx
> +          getMaxJobsPerTier(company?.category as CompanyCategory) && (
![image](https://github.com/dump-hr/ddays-app/assets/73669815/3eaf325e-925c-4a11-bf2d-2385b0a703d2)
sad sam nasao zas nije radilo - zasto smo ovo koristili u dto?

2024-02-14 22:02 UTC, bdeak4 commented on apps/sponsor/src/formSteps/Job/Job.tsx
> +          getMaxJobsPerTier(company?.category as CompanyCategory) && (
mislim da je razlog za to sto se drizzle tip ne moze direktno mapirat na `CompanyCategory` nego mora `\`${CompanyCategory}\``

2024-02-14 22:03 UTC, bdeak4 commented on apps/sponsor/src/pages/MaterialsPage/MaterialsPage.tsx
> +      {company && (
ima smisla, ok

2024-02-14 23:12 UTC, merged