Josipa saravnja/company crud
dump-hr/ddays-app pull request #22
Opened 2023-12-02 14:21 UTC by JosipaSaravanja

closes #6

2023-12-02 17:19 UTC, bdeak4 requested changes

2023-12-02 17:19 UTC, bdeak4 commented on apps/api/src/companies/companies.controller.ts
> +    const company = await this.companiesService.getOne(+id);
možemo koristit ParseIntPipe da odma pretvori id u broj i baci error ako nije broj
[docs.nestjs.com/pipes#binding-pipes](https://docs.nestjs.com/pipes#binding-pipes)

2023-12-08 01:30 UTC, dujesa requested changes
Prebacit samo dto u shareani paket, ostatak izgleda skroz dobro

2023-12-08 01:30 UTC, dujesa commented on apps/api/src/companies/dto/create-company.dto.ts
> +import { IsEnum, IsNumber, IsString } from 'class-validator';
Trebalo bi prebacit dtoove u package/types kao sta je napravljeno po primjeru za create i update eventa.

2023-12-08 01:30 UTC, dujesa commented on .vscode/settings.json
> +    "editor.formatOnPaste": true
nisan siguran jel namjerno ostavljeno ili ciljano, pa bacit oko jos jednom

2023-12-14 02:00 UTC, dujesa approved these changes

2023-12-14 02:01 UTC, merged