Frequently asked questions crud
dump-hr/ddays-app pull request #25
Opened 2023-12-04 06:56 UTC by ivojovanovic01

Napravljeno sve osim validacija

2023-12-05 14:09 UTC, bdeak4 requested changes
sve u svemu dobro je ali pogledaj ovih par komentara i trebalo bi ispraviti konflikte

2023-12-05 14:09 UTC, bdeak4 commented on apps/api/src/frequentlyAskedQuestion/frequentlyAskedQuestion.controller.ts
> +    @Param('id') id: string,
možemo koristit ParseIntPipe da odma pretvori id u broj i baci error ako nije broj
[docs.nestjs.com/pipes#binding-pipes](https://docs.nestjs.com/pipes#binding-pipes)

2023-12-05 14:09 UTC, bdeak4 commented on apps/api/src/frequentlyAskedQuestion/dto/update-frequentlyAskedQuestion.dto.ts
> +}
ove DTOove bi trebalo prebacit u `types` package tako da ih mozemo koristit i na frontendu. baci oko na #24 PR ili se javi @dujesa

2023-12-05 14:09 UTC, bdeak4 commented on apps/api/db/schema.ts
> +  answer: varchar('answer', { length: 255 }).notNull(),
koristit text tip stupca umjesto varchar sa length

![image](https://github.com/dump-hr/ddays-app/assets/32748145/fb403c09-e393-4d21-96a9-f2b60e1f2c34)

[postgresql.org/docs/current/datatype-character.html](https://www.postgresql.org/docs/current/datatype-character.html)

2023-12-06 10:02 UTC, dujesa requested changes
Resolveat conflicte i ide merge, good job
Validaciju cemo sa faq admin page taskom risit

2023-12-08 01:46 UTC, dujesa reviewed
Ima problema sa runnanjem migracije, vjv neki conflict se poremetia

2023-12-08 09:42 UTC, dujesa commented on apps/api/db/schema.ts
> +  text,
vec imas importano

2023-12-14 02:27 UTC, dujesa approved these changes

2023-12-14 02:28 UTC, merged