Events admin
dump-hr/ddays-app pull request #269
Opened 2024-03-11 20:37 UTC by tsiklic1

2024-03-11 20:47 UTC, bdeak4 requested changes
treba ispravit par sitnica, ovo ostalo sve top :+1:

2024-03-11 20:47 UTC, bdeak4 commented on apps/admin/src/api/event/useEventCreate.ts
> +  console.log(typeof dto.startsAt);
maknit

2024-03-11 20:47 UTC, bdeak4 commented on apps/api/db/migrations/meta/_journal.json
> +      "breakpoints": true
maknit ovo

2024-03-11 20:47 UTC, bdeak4 commented on apps/admin/src/pages/EventPage.tsx
> +                return;
fali remove akcija

2024-03-11 20:47 UTC, bdeak4 commented on apps/api/src/event/event.service.ts
>      const [createdEvent] = await db.insert(event).values(dto).returning();
ovaj dio mozes maknit zbog komentara iznad za eventform.tsx

2024-03-11 20:47 UTC, bdeak4 commented on apps/admin/src/forms/EventForm.tsx
> +    },
ovaj dio bi izbacia jer nikad necemo na ruke ubacivat kod, mozes samo zanemarit code zasad a kasnije bi samo napravia da se automatski generira
jer je uvik 1 event = 1 kod

2024-03-11 20:51 UTC, tsiklic1 commented on apps/admin/src/api/event/useEventCreate.ts
> +  console.log(typeof dto.startsAt);
✅

2024-03-11 20:51 UTC, tsiklic1 commented on apps/api/db/migrations/meta/_journal.json
> +      "breakpoints": true
✅

2024-03-11 20:52 UTC, tsiklic1 commented on apps/api/src/event/event.service.ts
>      const [createdEvent] = await db.insert(event).values(dto).returning();
✅

2024-03-11 20:52 UTC, tsiklic1 commented on apps/admin/src/forms/EventForm.tsx
> +    },
✅

2024-03-11 20:59 UTC, tsiklic1 commented on apps/admin/src/pages/EventPage.tsx
> +                return;
✅

2024-03-12 00:16 UTC, bdeak4 approved these changes
:fire_engine:

2024-03-12 00:16 UTC, merged