Roko perisic/dodat animaciju na social media botune
dump-hr/ddays-app pull request #394
Opened 2024-08-19 13:44 UTC by itsjozo1

2024-08-19 15:01 UTC, itsjozo1 commented
Dodano je da se social botun makne gore na hover

2024-08-25 09:12 UTC, lovretomic requested changes

2024-08-25 09:12 UTC, lovretomic commented on apps/web/src/components/FooterSection/FooterSection.module.scss
> +    &:hover {
ovo je okej rjesenje ali zbog te margine posli moras popravit linkedin. najbolja opcija cini mi se bila bi da ne minjas marginu, nego da na botune stavis position: relative i top: 0px; i onda na hover da je top recimo -5px

to je bolje jer margine mogu promijenit layout sta stvara problem za linkedin, a position djeluje samo na taj element neovisno o bilocem ostalom pa je efikasnije -- probaj tako

2024-09-15 09:34 UTC, lovretomic approved these changes

2024-09-15 09:34 UTC, merged