stavit iskidani papir na granice sekcija raspored i faq
dump-hr/ddays-app pull request #398
Opened 2024-08-20 14:04 UTC by itsjozo1

2024-08-21 10:05 UTC, bdeak4 approved these changes
LGTM

2024-08-25 09:52 UTC, lovretomic requested changes

2024-08-25 09:52 UTC, lovretomic commented on apps/web/src/components/Testimonial/Testimonial.module.scss
> +    background-image: url(../../assets/images/noise.webp);
ovdje cak ne ide grain koliko vidim iz figme. zbog ovog se potencijalno misa sa faq breakerom

2024-08-25 09:53 UTC, lovretomic commented
![image](https://github.com/user-attachments/assets/15040cf2-3858-4ec5-b0f3-6aea7152d45c)
ovdje se malo preklapaju

2024-09-15 14:03 UTC, lovretomic commented
![image](https://github.com/user-attachments/assets/1609286f-c161-475a-ae91-e1d50c459d2d)
ne znam jel i tebi ovako ali na iskidanom dijeluj iznad faq-a mi fali grain

2024-09-23 13:31 UTC, lovretomic approved these changes
lgtm

2024-09-23 13:31 UTC, merged