Updated SpeakerCard @ and company name are devided from title
dump-hr/ddays-app pull request #399
Opened 2024-08-23 15:40 UTC by andrea-zecevic

2024-09-05 09:03 UTC, tsiklic1 requested changes
Ne znan jel u neki review neko pisa da ovo triba ovako, al u ovom dizajnu za landing nisu stvari ovakve: 
https://www.figma.com/design/lsXN5WArBu7qnbbaHuEPJh/Dev-Handoff?node-id=1-41&node-type=CANVAS&m=dev

2024-09-05 09:03 UTC, tsiklic1 commented on apps/web/src/components/Testimonial/Testimonial.tsx
> +          <p className={c.company}>@ {company}</p>
ista stvar ka i gori, u dizajnu ove stvari idu u isti red

2024-11-08 11:59 UTC, tsiklic1 approved these changes

2024-11-08 15:13 UTC, lovretomic approved these changes

2024-11-08 15:13 UTC, merged