New input component
dump-hr/ddays-app pull request #432
Opened 2024-11-18 14:19 UTC by andrea-zecevic

Link na figmu: https://www.figma.com/design/iRoQbImFMo9G8kSouAcL3d/DLS---DD-App?node-id=21-91&node-type=canvas&m=dev

Ovaj dotMaker san kopirala iz web app-a.  Nisan sigurna izgledaju li dobro te točkice u defaultu. U figmi su ko neki kvadratići. 

#430

2024-12-16 18:30 UTC, andrea-zecevic commented
Popravljeno

2024-12-22 22:04 UTC, lovretomic requested changes

2024-12-22 22:04 UTC, lovretomic commented on apps/app/src/components/Input/Input.tsx
> +export const Input = ({
ja bi da dodamo animaciju. konzultira san se s mihaelom, rekla je da ako imamo vrimena da bi bilo dobro. u tvom konkretnom slucaju, napravili bi kao da bude kao [basic text field > standard](https://mui.com/material-ui/react-text-field/#basic-textfield)

mozda ti pomogne:
- https://medium.com/@bhanutejkalla/animate-input-placeholder-text-on-focus-5d841bc23e9f
- https://jacobruiz.com/blog/2021/2/11/how-to-transition-placeholder-text-into-a-label-in-react-floating-label-inputs
- https://dev.to/rafacdomin/creating-floating-label-placeholder-for-input-with-reactjs-4m1f

2025-01-04 22:49 UTC, andrea-zecevic commented on apps/app/src/components/Input/Input.tsx
> +} & React.HTMLProps<HTMLInputElement>;
done

2025-01-06 22:41 UTC, merged