Tsiklic1/common components
dump-hr/ddays-app pull request #441
Opened 2024-12-12 16:27 UTC by tsiklic1

Added button, notification and toggle button common components

2024-12-13 17:46 UTC, lovretomic requested changes
Evo neke promjenice sta san uspia povatat. Opcenito super napravljeno.

2024-12-13 17:46 UTC, lovretomic commented on apps/app/vite.config.ts.timestamp-1732121991007-a6eec8f4f3a39.mjs
> +import react from "file:///C:/Users/tomas/DUMP/ddays-app/ddays-app/node_modules/@vitejs/plugin-react/dist/index.mjs";
ova dva filea mislim da su visak pa ih eliminiraj

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/components/Button/Button.tsx
> +  active?: boolean;
je li ovo komplementarno s `handlers.disabled`? ako je onda bi maka taj prop i koristia nativno

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/components/Button/Button.tsx
> +  ...handlers
Jedan od ovih handlera je i `className`. Ako se u instancu komponente posalje npr className="botun" onda ti stilovi pregaze sve tvoje i potencijalno ne radi kako treba. tu bi samo za svaki slucaj da bude dobro u ovaj clsx koji saljes u button doda i [handlers.className] da se uvik primjeni, mislim da bi to bilo sve za to. P.S. ovo je bitno za slanje width propertyja preko scss filea da se ne treba u style handler radit nista posebno

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/App.tsx
> +      <Button variant={'beige'}>Click me</Button>
Fali mi tip botuna za bodove sa zvjezdicom. Tu bi doda prop koji kontrolira radi li se o takvom tipu botuna, i onda ako je da je obavezno uz to poslat i broj bodova (tj. poigrat se sa kondicioniranim typeom komponente)

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/App.tsx
> +      <Button variant={'beige'}>Click me</Button>
Takoder da se moze i na obican botun dodat ikonica slijeva.
![image](https://github.com/user-attachments/assets/8c01f166-7d1c-442a-859c-5df913dae6a6)

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/components/ToggleButton/ToggleButton.module.scss
> +    border-color 0.2s ease;
jako lijepo

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/components/Notification/Notification.module.scss
> +  padding: 32px 24px;
Ubija bi ovo. Mislim da je bolje da se o tome brine osoba koja bude radila page. Nebi to reka da nije u figmi komponenta po sebi napravljena bez paddinga iako se s njim kasnije koristi, pa neka pratimo tocno onako kako je naglaseno. Ovo bi sve pratia tocno tako kako je jer nismo sigurni 100 % kako bi trebala izgledat na webu u kojem mozda taj padding nikad nece trebat. Inace komponenta skroz okej cini mi se.

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/App.tsx
> +    time: '19 min ago',
Za ovo bih uzea pretpostavku da ce format podatka iz baze bit timestamp. Odma napravi funkciju koja racuna vrijeme proslo od slanja notifikacije. Ako ti bude nejasno koji je format recimo za sate ili dane, javi mi ili se konzultiraj odma s Mihaelom.

2024-12-13 17:46 UTC, lovretomic commented on apps/app/src/App.tsx
> +const notifications = [
Samo kad dobijes approved review nemoj zaboravit sve ovo (tj. testne podatke i komponente na ovoj stranici) izbrisat da ne bude konflikata s drugim branchevima.

2024-12-14 17:02 UTC, tsiklic1 commented on apps/app/src/components/Notification/Notification.module.scss
> +  padding: 32px 24px;
✅

2024-12-14 17:02 UTC, tsiklic1 commented on apps/app/src/components/Button/Button.tsx
> +  ...handlers
✅

2024-12-14 17:15 UTC, tsiklic1 commented on apps/app/src/App.tsx
> +    time: '19 min ago',
✅

2024-12-14 20:53 UTC, tsiklic1 commented on apps/app/vite.config.ts.timestamp-1732121991007-a6eec8f4f3a39.mjs
> +import react from "file:///C:/Users/tomas/DUMP/ddays-app/ddays-app/node_modules/@vitejs/plugin-react/dist/index.mjs";
✅

2024-12-14 20:53 UTC, tsiklic1 commented on apps/app/src/components/Button/Button.tsx
> +  active?: boolean;
✅

2025-01-02 12:12 UTC, lovretomic approved these changes

2025-01-02 12:12 UTC, merged