Drmodun/sponsor crud
dump-hr/ddays-app pull request #48
Opened 2023-12-15 00:37 UTC by drmodun

closes #31 
this Pr consists od the sponsor endpoints for the companies api, and the following database changes associated to it, it also has a dto for every single request and every request modifies exactly one property so it can be updated on demand and not all at once

this pr also adds authenthication with jwts for companies, I did it in the way I thought was good, but if someone suggests something better we will do that. I know this maybe should have been two pr-s, but I didnt wanna splti tasks since I may not be as available later

2023-12-19 11:14 UTC, bdeak4 requested changes
sve u svemu jako dobro odrađeno :clap: 
baci oko na ovih par komentara

2023-12-19 11:14 UTC, bdeak4 commented on apps/api/src/auth/auth.module.ts
> +      signOptions: { expiresIn: '24h' },
pošto nemamo neku jwt refresh logiku ovaj expires bi prebacia na 14 dana ili tako nesto

2023-12-19 11:14 UTC, bdeak4 commented on apps/api/src/auth/sponsor/jwt.strategy.ts
> +    };
dodat `role: sponsor` u jwt tako da mozemo lako neke endpointe ograniciti npr samo za role sponsor

2023-12-19 11:14 UTC, bdeak4 commented on apps/api/src/companies/companies.controller.ts
> +  async addSponsorDescription(
mozda maknit sponsor prefix i sa putanja i iz imena funkcija posto sponsor=company

2023-12-19 11:14 UTC, bdeak4 commented on apps/api/src/companies/companies.controller.ts
> +    @Req() req: any,
za ovaj req se moze staviti `Request` tip

2023-12-19 11:14 UTC, bdeak4 commented on apps/api/src/companies/companies.controller.ts
> +    @Req() req: any,
ili bi cak bilo dobro napraviti `AuthenticatedRequest` di se extenda ovaj obicni request sa `JwtPayload` tipom za `req.user`

2023-12-19 11:14 UTC, bdeak4 commented on packages/types/src/dto/auth/sponsor.ts
> +    officialEmail: string;
razdvojit ove propertyje sa praznom linijom, i gore između funkcije i importa
samo izgleda malo preglednije

2023-12-19 11:14 UTC, bdeak4 commented on packages/types/src/dto/company/update.ts
> +  class UpdateCompanyDto extends PartialType(CreateCompanyDto) {} //TODO: Possibly exclude password and email here, maybe make a specific enpoint for that
frontend nam eksplodira kad se importaju ovi nestjs paketi unutar types :sweat_smile:  tako da imamo ban na PartialType

2023-12-19 11:14 UTC, bdeak4 commented on packages/types/src/dto/sponsor/update.ts
> +//sponsor ids are temporary, in the future the sponsor id will be fetched from the jwt token or other auth
maknit komentar, pretpostavljan da je vec riseno posto nema sponsor id fieldova?

2023-12-19 11:18 UTC, bdeak4 commented on apps/api/src/companies/companies.service.ts
> +      throw new NotFoundException('company not found');
veliko slovo za err message

2023-12-25 13:18 UTC, drmodun commented on apps/api/src/auth/auth.module.ts
> +      signOptions: { expiresIn: '24h' },
stavia 14 dana u satima

2023-12-25 13:20 UTC, drmodun commented on apps/api/src/companies/companies.controller.ts
> +  async addSponsorDescription(
:white_check_mark:

2023-12-25 13:21 UTC, drmodun commented on apps/api/src/companies/companies.service.ts
> +      throw new NotFoundException('company not found');
:white_check_mark:

2023-12-25 13:22 UTC, drmodun commented on packages/types/src/dto/auth/sponsor.ts
> +    officialEmail: string;
:white_check_mark:

2023-12-25 13:23 UTC, drmodun commented on packages/types/src/dto/company/update.ts
> +  class UpdateCompanyDto extends PartialType(CreateCompanyDto) {} //TODO: Possibly exclude password and email here, maybe make a specific enpoint for that
bilo bi dobro vidit ima li koja alternativa da neku klasu gleda da je cijela nullable ako se to moze, cisto msm da ce dosta neuredno / naporno biti ovako radit

2023-12-25 13:27 UTC, drmodun commented on packages/types/src/dto/sponsor/update.ts
> +//sponsor ids are temporary, in the future the sponsor id will be fetched from the jwt token or other auth
riseno je jer se preko requesta dobije sponsor id, to mi je zna bit problem na nekim drugim apijima di mi treba vise id-ova pa bi ponekad triba stavit u dto, zato san to ovde napisa

2023-12-25 13:27 UTC, drmodun commented on apps/api/src/auth/sponsor/jwt.strategy.ts
> +    };
posto msm da nemamo neki specificni enum za ovo moze samo string sponsor?

2023-12-25 13:36 UTC, drmodun commented on apps/api/src/companies/companies.controller.ts
> +    @Req() req: any,
evo pokusa san napravit nes ovako, pogle i kazi jes to mislia a ako ne bude radilo javi

2023-12-27 20:00 UTC, bdeak4 requested changes

2023-12-27 20:00 UTC, bdeak4 commented on apps/api/db/schema.ts
> +  email: text('official_email').notNull().unique(), //TODO: Use this for stuff like password reset and email validation
prominit i ime columna u bazi

2023-12-27 20:00 UTC, bdeak4 commented on apps/api/src/auth/sponsor/jwt.strategy.ts
> +    };
da

2023-12-27 20:00 UTC, bdeak4 commented on apps/api/src/auth/auth.module.ts
> +      signOptions: { expiresIn: '336h' },
trebalo bi radit i samo `14d` ja mislim

2023-12-27 20:00 UTC, bdeak4 commented on apps/api/src/companies/companies.controller.ts
> +    @Req() req: any,
dobro je ovo samo file mozes nazvat `auth.dto.ts` ili prebacit u neki drugi jer nema potrebe za authenitacatedRequest.ts

2023-12-27 20:00 UTC, bdeak4 commented on apps/api/src/companies/companies.controller.ts
> +  async addSponsorDescription(
treba maknit i iz imena metoda

2023-12-27 20:00 UTC, bdeak4 commented on packages/types/src/dto/company/update.ts
> +  class UpdateCompanyDto extends PartialType(CreateCompanyDto) {} //TODO: Possibly exclude password and email here, maybe make a specific enpoint for that
istina, iako nisam siguran jel ovo trenutno radi dobro ako koristimo partial type tj oce li se recimo description settat na null ako ne posaljemo u update (ovo bi bilo dobro provjerit ako imas volje)

2023-12-27 20:00 UTC, bdeak4 commented on apps/api/src/auth/auth.service.ts
> +      throw new BadRequestException('email is required');
veliko slovo

2024-01-02 19:45 UTC, merged

2024-01-03 00:58 UTC, drmodun commented on apps/api/db/schema.ts
> +  email: text('official_email').notNull().unique(), //TODO: Use this for stuff like password reset and email validation
ovo je promijenjeno u buducem pr-u, nebi tia radit nove konfilkte pa necu ovdi minjat