Drmodun/interest crud
dump-hr/ddays-app pull request #49
Opened 2023-12-15 12:03 UTC by drmodun

closes #29 
This pr consists of the crud endpoints for the interests resource and the schema structure of interests along with its relations

2023-12-19 11:19 UTC, bdeak4 requested changes
sve u svemu LGTM, baci oko na kom

2023-12-19 11:19 UTC, bdeak4 commented on apps/api/src/interests/interests.controller.ts
> +    const Interests = await this.interestsService.getAll();
prebacit u malo slovo ime var

2023-12-19 11:19 UTC, bdeak4 commented on apps/api/src/interests/interests.controller.ts
> +    const Interest = await this.interestsService.getOne(id);
prebacit u malo slovo ime var

2023-12-19 11:19 UTC, bdeak4 commented on packages/types/src/dto/interest/update.ts
> +  class UpdateInterestDto extends PartialType(CreateInterestDto) {}
isto, ne smijemo koristit ovaj partial type unutar types pa eksplicitno raspisi dto

2023-12-19 14:13 UTC, dujesa requested changes
Sredit conflicte uz Bartolove kom

2023-12-25 13:13 UTC, drmodun commented on apps/api/src/interests/interests.controller.ts
> +    const Interests = await this.interestsService.getAll();
:white_check_mark:

2023-12-25 13:13 UTC, drmodun commented on apps/api/src/interests/interests.controller.ts
> +    const Interest = await this.interestsService.getOne(id);
:white_check_mark:

2023-12-25 13:13 UTC, drmodun commented on packages/types/src/dto/interest/update.ts
> +  class UpdateInterestDto extends PartialType(CreateInterestDto) {}
:white_check_mark:

2024-01-02 19:49 UTC, merged