Survey question page
dump-hr/ddays-app pull request #62
Opened 2023-12-23 07:28 UTC by tsiklic1

closes #28

2023-12-27 20:14 UTC, bdeak4 requested changes
za modal treba dodat da se closea na success submit
za delete bi bilo bolje koristit samo onaj `prompt` koji pita are you sure

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +  console.log('api', data);
maknit

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +    (data: CreateSurveyQuestionDto) => createSurveyQuestion(data),
ovo moze cak bez ovog `(data) =>...` nego samo createSurveyQuestions pa ce on sam prepoznat tip podataka itd

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +        toast.error("Couldn't create survey question");
ovdje mozemo prikazat neku smislenu poruku koja nam se ionako posalje s backenda

```
    onError: (error: string) => {
      toast.error(error);
    },
```

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useDeleteSurveyQuestion.ts
> +    },
isto dodat onError

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useFetchSurveyQuestions.ts
> +    }[]
zasto ne samo SurveyQuestion[], i zasto ne prebacit ovaj survey question dto u shareane tipove

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useUpdateSurveyQuestion.ts
> +    req.surveyQuestion,
mozes samo prosljedit 2 parametra pa da prvi bude id a drugi surveyQuestion tako ce mozda izgledat malo cisce nego s `req`

2023-12-27 20:14 UTC, bdeak4 commented on apps/admin/src/components/InputHandler/InputHandler.tsx
> +      ); //TODO: toma <SelectInput/>
maknit ako je riseno?

2023-12-28 16:28 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +  console.log('api', data);
✅

2023-12-28 16:29 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +    (data: CreateSurveyQuestionDto) => createSurveyQuestion(data),
✅

2023-12-28 16:29 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +        toast.error("Couldn't create survey question");
✅

2023-12-28 16:30 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useDeleteSurveyQuestion.ts
> +    },
✅

2023-12-28 16:33 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useFetchSurveyQuestions.ts
> +    }[]
✅

2023-12-28 16:48 UTC, tsiklic1 commented on apps/admin/src/components/InputHandler/InputHandler.tsx
> +      ); //TODO: toma <SelectInput/>
✅

2023-12-28 20:09 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useUpdateSurveyQuestion.ts
> +    req.surveyQuestion,
✅

2023-12-29 17:23 UTC, bdeak4 requested changes

2023-12-29 17:23 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +  const data = await api.post(`/survey-questions`, surveyQuestion);
dodat return type

2023-12-29 17:23 UTC, bdeak4 commented on apps/admin/src/api/SurveyQuestions/useDeleteSurveyQuestion.ts
> +  const data = await api.delete(`/survey-questions/${id}`);
dodat return type

2023-12-29 17:23 UTC, bdeak4 commented on apps/admin/src/api/index.ts
>      message: string;
maknit ovaj message key

2023-12-29 17:23 UTC, bdeak4 commented on apps/admin/src/components/SelectInput/SelectInput.tsx
> -  label: string;
zasto je optional

2023-12-29 17:23 UTC, bdeak4 commented on apps/admin/src/components/Table/Table.tsx
> +  data,
data = [] i onda se moze maknit {!!data && check

2023-12-29 17:23 UTC, bdeak4 commented on apps/admin/src/pages/SurveyQuestionsPage/SurveyQuestionsPage.tsx
> +        surveyQuestionType: questionToEdit?.surveyQuestionType,
ne triba upitnik

2023-12-29 17:23 UTC, bdeak4 commented on apps/api/.env
> +DATABASE_URL=postgres://dumpovac:dump123@localhost:3001/ddays
maknit space

2023-12-29 17:26 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useCreateSurveyQuestion.ts
> +  const data = await api.post(`/survey-questions`, surveyQuestion);
✅

2023-12-29 17:27 UTC, tsiklic1 commented on apps/admin/src/api/SurveyQuestions/useDeleteSurveyQuestion.ts
> +  const data = await api.delete(`/survey-questions/${id}`);
✅

2023-12-29 17:28 UTC, tsiklic1 commented on apps/admin/src/api/index.ts
>      message: string;
✅

2023-12-29 17:28 UTC, tsiklic1 commented on apps/admin/src/components/SelectInput/SelectInput.tsx
> -  label: string;
✅

2023-12-29 17:29 UTC, tsiklic1 commented on apps/admin/src/components/Table/Table.tsx
> +  data,
✅

2023-12-29 17:30 UTC, tsiklic1 commented on apps/admin/src/pages/SurveyQuestionsPage/SurveyQuestionsPage.tsx
> +        surveyQuestionType: questionToEdit?.surveyQuestionType,
✅

2023-12-29 17:32 UTC, bdeak4 approved these changes

2023-12-29 17:32 UTC, merged