Admin: Events page
dump-hr/ddays-app pull request #65
Opened 2023-12-31 11:14 UTC by lovretomic

Completed the events page in the admin pannel ( closes #9 ):
- added form modal
- added creating, editing and deleting events
- managed time differences
- frontend validation

TODO: generating codes

2024-01-02 19:57 UTC, fdoljanin commented
Povećat dimenzije modala ili nešto da ne moram scrollat za dodat event. Možda napravit modal takvim da ima x u gornjem desnom ćošku, a ispod botun za potvrdit akciju? Također, ako slučajno kliknem na pozadinu, izgubim sav progress. Tu bih da se ili pita korisnika je li siguran da želi izać iz editora, ili da ostane zapamćeno stanje.

![image](https://github.com/dump-hr/ddays-app/assets/73669815/8407731c-0ef2-4083-a5e4-8ac70af11a61)

2024-01-02 20:39 UTC, fdoljanin requested changes

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/pages/EventsPage/AddEditEventModal.tsx
> +            placeholder='Unesi mjesto'
Ovo je iz 2021 kad su daysi bili parcijalno online, sad bih izbacio eventplace i iz baze i svega, nepotrebno, sve je uživo

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/pages/EventsPage/AddEditEventModal.tsx
> +      toast.error('Poveznica na video mora biti unesena.');
ne mora, ovo unosimo nakon daysa

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/pages/EventsPage/AddEditEventModal.tsx
> +    } else if (data.maxParticipants > 1000) {
lol y

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/pages/EventsPage/AddEditEventModal.tsx
> +      toast.error('Opis ne smije imati više od 50 znakova.');
samo makni sve ove constraintove

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/components/SelectInput/SelectInput.tsx
> +      <label htmlFor={handlers.id} className={c.selectLabel}>
Zašto ovo? Nema smisla id property zvat ko html-ov id na svakom parentu, bolje koristiti ovaj reactov useId jer on sam smisli unique za komponentu pa ne moraš sam hendlat (label da je povezan s inputom). Ili imaš neki drugi razlog?

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/api/useFetchEvents.ts
> +type Event = {
već ga imaš definirano

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/api/useFetchEvent.ts
> +type Event = {
shared

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/pages/EventsPage/AddEditEventModal.tsx
> +        <div>
Svi ovi inputi i stateovi na njima su nepotrebni, napravili smo InputHandlere i QuestionType za ovakve stvari. Tada možeš vrlo jednostavno u objektu definirati pitanja (čak i constraintove na odgovore) pa komponenta i RHF vrlo jednostavno sami hendlaju.

2024-01-02 20:39 UTC, fdoljanin commented on apps/admin/src/pages/EventsPage/EventsPage.tsx
> +      action: (row: object) => {
Zašto object, možeš TableDataRow

2024-01-05 23:16 UTC, bdeak4 requested changes

2024-01-05 23:16 UTC, bdeak4 commented on apps/api/.env
> -DATABASE_URL=postgres://dumpovac:dump123@localhost:3001/ddays
stvari u .env ne bi trebali minjat jer su to defaultne postavke nego napravit .env.local u kojem su custom postavke

(ovo je moja greska jer izgleda da nije ni radilo do sad al sad cu popravit)

2024-01-06 00:04 UTC, fdoljanin requested changes

2024-01-13 09:20 UTC, lovretomic commented on apps/admin/src/pages/EventsPage/TimeHelper.ts
> +class TimeHelper {
zaminia san za sad samo format, mislin da je duje reka da se krivo zapisuju datetimeovi u bazi, pa su ove ostale funkcije samo tu kako bi privremeno napravile da radi dohvacanje iz baze. prespecifican je use case koji dayjs ne pokriva koliko mi se cini, svakako bi se najvjerojatnije tribalo maknit nekad u buducnosti

2024-01-13 18:15 UTC, bdeak4 approved these changes

2024-01-13 18:24 UTC, bdeak4 approved these changes

2024-01-13 18:24 UTC, merged