merge Drmodun/interests to main
dump-hr/ddays-app pull request #77
Opened 2024-01-05 23:25 UTC by bdeak4

2024-01-10 14:15 UTC, drmodun commented
dovrsia pr, pogledajte jel sve radi dobro, closes #30

2024-01-13 14:52 UTC, fdoljanin commented on yarn.lock
> -mime-types@^2.1.12, mime-types@^2.1.27, mime-types@^2.1.35, mime-types@~2.1.24, mime-types@~2.1.34:
👀

2024-01-13 14:54 UTC, fdoljanin commented on apps/api/src/companies/companies.controller.ts
> -  async getSponsorFormStatus(@Req() req: AuthenticatedRequest) {
ovo treba ostat

2024-01-13 15:12 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +    if (!editInterestForm.formState.isValid) {
nepotrebno, svakako se validira na handlesubmit prije nego se ovo pozove

2024-01-13 15:49 UTC, fdoljanin requested changes

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +      <Modal
Estetski su gadni ovi modali

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +  const [isOpenAddModal, setIsOpenAddModal] = useState(false);
Kako ovdje imaš 3 modala, možda da imaš state koji sprema koji je trenutno otvoren

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +  const [isOpenAddModal, setIsOpenAddModal] = useState(false);
I onda spremaš u neki state trenutni interes

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +  }, [interestToEdit]);
warning

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +    if (!createInterestForm.formState.isValid) {
isto ko gore

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +          Dodaj
ovo na dno

2024-01-13 15:49 UTC, fdoljanin commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +          setIsOpenAddModal(!isOpenAddModal);
prev

2024-01-13 15:54 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +    if (!editInterestForm.formState.isValid) {
:white_check_mark:

2024-01-13 15:56 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +  const [isOpenAddModal, setIsOpenAddModal] = useState(false);
iduci task

2024-01-13 15:56 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +    if (!createInterestForm.formState.isValid) {
:white_check_mark:

2024-01-13 16:16 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +          setIsOpenAddModal(!isOpenAddModal);
:white_check_mark:

2024-01-13 16:16 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +          Dodaj
:white_check_mark:

2024-01-13 16:37 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +  }, [interestToEdit]);
:white_check_form:

2024-01-13 16:44 UTC, drmodun commented on apps/api/src/companies/companies.controller.ts
> -  async getSponsorFormStatus(@Req() req: AuthenticatedRequest) {
:white_check_mark:

2024-01-13 16:45 UTC, drmodun commented on yarn.lock
> -mime-types@^2.1.12, mime-types@^2.1.27, mime-types@^2.1.35, mime-types@~2.1.24, mime-types@~2.1.34:
nez sta je ovo il jel bitno

2024-01-13 16:57 UTC, drmodun commented on apps/admin/src/pages/InterestsPage/InterestsPage.tsx
> +      <Modal
idem prvo mergat main pa se kasnije brinut za ovo, bitniji su mi konflikti

2024-01-13 23:36 UTC, merged