Drmodun/companies page
dump-hr/ddays-app pull request #89
Opened 2024-01-07 21:15 UTC by drmodun

closes #10 
this pr consists of the companies page, along with several other QOL improvements to companies and interests endpoint and a textarea element

2024-01-11 21:23 UTC, bdeak4 requested changes

2024-01-11 21:23 UTC, bdeak4 commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    if (interests) {
```
if (!interests) return;
```

2024-01-11 21:23 UTC, bdeak4 commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    if (companyToEdit) {
early return

2024-01-11 21:23 UTC, bdeak4 commented on apps/api/src/companies/companies.service.ts
> +  }
koristit normalne ifove pls

2024-01-11 21:23 UTC, bdeak4 commented on apps/api/src/interests/interests.controller.ts
> +    }
prebacit u servis

2024-01-12 17:53 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    console.log('loading');
:white_check_mark:

2024-01-12 17:54 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    if (interests) {
:white_check_mark:

2024-01-12 17:55 UTC, drmodun commented on apps/api/.env
> +DATABASE_URL=postgres://postgres:postgres@localhost:5432/ddays
sorry .local mi do sad nie radia pa sam zaboravia malo

2024-01-12 17:56 UTC, drmodun commented on apps/api/src/companies/companies.controller.ts
> +    if (!company) throw new NotFoundException('Company not found');
✅

2024-01-12 17:57 UTC, drmodun commented on apps/api/src/interests/interests.controller.ts
> +    }
✅

2024-01-12 17:57 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +  const [companyToEditId, setCompanyToEdit] = useState<number>(1);
✅

2024-01-12 17:57 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    if (companyToEdit) {
✅

2024-01-12 18:00 UTC, drmodun commented on apps/api/src/companies/companies.service.ts
> +  }
✅

2024-01-13 17:15 UTC, fdoljanin requested changes

2024-01-13 17:15 UTC, fdoljanin commented on packages/types/src/dto/company/create.ts
> +    description?: string;
stavi da nije obavezno (skoro nista)

2024-01-13 17:15 UTC, fdoljanin commented on packages/types/src/dto/company/create.ts
> +    sponsorCategory?: string;
i ovo je isto optional

2024-01-13 17:15 UTC, fdoljanin commented on packages/types/src/dto/company/create.ts
> +    description?: string;
IsOptional

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +          setIsOpenAddModal(!isOpenAddModal);
prev

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +      <Table
malo pogledaj razmake i to

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    createCompany(data);
stavi na then, ako uspije, da se modal zatvori i resetira

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    if (!createCompanyForm.formState.isValid) {
valjda obrnuto al ionako obrisi ovo

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    editCompanyForm.reset({
ovo cak ne bi na useeffect nego na handler klika da se edituje forma

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +  const { mutate: deleteCompany } = useDeleteCompany();
malo rasporedi razmake

2024-01-13 17:15 UTC, fdoljanin commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +      interests: interestsForCompany?.map((interest) => interest.id.toString()),
Pa samo ih fetchaj odmah s kompanijom, lako je to u Drizzle, include

2024-01-13 17:17 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +          setIsOpenAddModal(!isOpenAddModal);
:white_check_mark:

2024-01-13 17:39 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    if (!createCompanyForm.formState.isValid) {
:white_check_mark:

2024-01-13 17:41 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    createCompany(data);
:white_check_mark:

2024-01-13 17:41 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +      <Table
:white_check_mark:

2024-01-13 17:41 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +  const { mutate: deleteCompany } = useDeleteCompany();
:white_check_mark:

2024-01-13 17:42 UTC, drmodun commented on apps/api/src/companies/companies.service.ts
> +    console.log(interestIds, companyId);
:white_check_mark:

2024-01-13 17:43 UTC, drmodun commented on packages/types/src/dto/company/create.ts
> +    sponsorCategory?: string;
:white_check_mark:

2024-01-13 17:43 UTC, drmodun commented on packages/types/src/dto/company/create.ts
> +    description?: string;
:white_check_mark:

2024-01-13 17:52 UTC, drmodun commented on packages/types/src/dto/company/read.ts
> +type SponsorType =
ovo nismo mogli fixat nema veze

2024-01-13 17:52 UTC, drmodun commented on packages/types/src/dto/company/update.ts
> +  IsOptional,
:white_check_mark:

2024-01-13 17:53 UTC, drmodun commented on packages/types/src/dto/interest/read.ts
> +export type eventThemeType = 'dev' | 'design' | 'tech' | 'marketing';
:white_check_mark:

2024-01-13 18:17 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +      interests: interestsForCompany?.map((interest) => interest.id.toString()),
za kasnije TODO

2024-01-13 18:25 UTC, drmodun commented on apps/api/src/companies/companies.service.ts
> +    const numericalInterests = createCompanyDto.interests.map(
fix multiple select type issues

2024-01-13 18:45 UTC, drmodun commented on apps/admin/src/pages/CompaniesPage/CompaniesPage.tsx
> +    editCompanyForm.reset({
ne moze sada kada fetchamo interese svako malo, vjv je i ovo TODO zajedno sa onim ostalim

2024-01-13 23:25 UTC, merged